-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 00:51:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema банк
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema банк
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `банк` DEFAULT CHARACTER SET utf8 ;
USE `банк` ;

-- -----------------------------------------------------
-- Table `банк`.`account_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `банк`.`account_detail` (
  `card_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`card_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `банк`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `банк`.`cards` (
  `card_number` INT NOT NULL,
  `card_code` VARCHAR(4) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `банк`.`balance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `банк`.`balance` (
  `card_id` INT NOT NULL,
  `balance` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`card_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
